### ISSUE TITLE
Compilation errors on M1 Mac

### ISSUE THREAD

**Issue by ken-matsui** [samkaufman/morello#2]
I could not use morello on M1 Mac caused of the following errors. This is not what I saw when I first tried morello, so the errors at that time might have been fixed upstream. That being said, I still see the following errors related to CPU architecture.

###### Tested on

```console
$ echo "macOS $(sw_vers -productVersion) $(sw_vers -buildVersion) $(uname -m)"
macOS 13.2.1 22D68 arm64
```

###### CLANG environment variable

```console
$ echo $CLANG
/opt/homebrew/Cellar/llvm/15.0.7_1/bin/clang
```

###### Actual Errors

```console
$ poetry run ./scripts/main.py --cache seed_cache.pkl matmul 4 4 4
The currently activated Python version 3.11.2 is not supported by the project (>=3.9,<=3.11).
Trying to find and use a compatible version.
Using python3 (3.10.10)
clang-15: warning: argument unused during compilation: '-mavx2' [-Wunused-command-line-argument]
In file included from /var/folders/l3/vsszss2s3p98jhhvrn54kwhm0000gn/T/tmpzbuaag3d/main.c:7:
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/immintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
#error "This header is only meant to be used on x86 and x64 architecture"
 ^
In file included from /var/folders/l3/vsszss2s3p98jhhvrn54kwhm0000gn/T/tmpzbuaag3d/main.c:7:
In file included from /opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/immintrin.h:21:
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
#error "This header is only meant to be used on x86 and x64 architecture"
 ^
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:54:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:133:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and intege
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:163:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and intege
    return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:193:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and intege
    return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:220:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and intege
    return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:243:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and intege
    return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:264:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and intege
    return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:291:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and intege
    return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:314:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and intege
    return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:335:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and intege
    return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:356:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and intege
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:377:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and intege
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:398:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and intege
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:420:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and intege
    return (__m64)__builtin_ia32_paddsb((__v8qi)__m1, (__v8qi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:443:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and intege
    return (__m64)__builtin_ia32_paddsw((__v4hi)__m1, (__v4hi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:465:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and intege
    return (__m64)__builtin_ia32_paddusb((__v8qi)__m1, (__v8qi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/llvm/15.0.7_1/lib/clang/15.0.7/include/mmintrin.h:487:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and intege
    return (__m64)__builtin_ia32_paddusw((__v4hi)__m1, (__v4hi)__m2);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Traceback (most recent call last):
  File "/Users/kmatsui/Dropbox/GitHub/samkaufman/morello/./scripts/main.py", line 327, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/kmatsui/Dropbox/GitHub/samkaufman/morello/./scripts/main.py", line 285, in main
    benchmarked_runtimes = await asyncio.gather(*[get_time(im) for im in scheds])
  File "/Users/kmatsui/Dropbox/GitHub/samkaufman/morello/./scripts/main.py", line 283, in get_time
    return await system_config.current_target().time_impl_robustly(imp)
  File "/Users/kmatsui/Dropbox/GitHub/samkaufman/morello/morello/system_config/base.py", line 85, in time_impl_robustly
    artifact = await self.build_impl(impl)
  File "/Users/kmatsui/Dropbox/GitHub/samkaufman/morello/morello/system_config/cpu.py", line 145, in build_impl
    raise Exception(f"Clang exited with code {clang_proc.returncode}")
Exception: Clang exited with code 1
```

**Comment by samkaufman** [comment]
@ken-matsui Thank you! This makes perfect sense. I'll make two changes once I get a second.

- [ ] Make sure main.py prints the Impl even if codegen fails.
- [ ] Add a mode for M1's. This probably won't support M1 vector intrinsics natively at first, but we can at least generate scalar code and let Clang do its auto-vectorization magic.
